### ISSUE TITLE
Hostnames are not populated - xlsx and docx

### ISSUE THREAD

**Issue by shall1569** [TheGroundZero/openvasreporting_server#3]
Tried to go through some of the python code and figure out how the "Hostname" field was being populated.. but alas I am no expert

When exporting to xlsx, there is a Host name field on the vulnerability tabs.
This is just marked as "-"

Ask questions, and I will try and explain more if needed

**Comment by TheGroundZero** [comment]
Hi @shall1569 

This tool is to set up a listener that can automated reports that are sent after finishing a scan.
The actual exporting to xlsx files is done through the [OpenVAS Reporting](https://github.com/TheGroundZero/openvasreporting) package.

The code for creating the sheets for each discovered vulnerability can be found in [export.py](https://github.com/TheGroundZero/openvasreporting/blob/master/openvasreporting/libs/export.py#L251).
[Line 337](https://github.com/TheGroundZero/openvasreporting/blob/master/openvasreporting/libs/export.py#L337) is the one that fills the hostname cell. `-` is entered if the scan data did not include a hostname.

I copied the hostname part from cr0hn's [Openvas2Report](https://github.com/cr0hn/openvas_to_report).
However, I think the scan data actually never includes a hostname, even if one is discovered by the scan, which I believe is an issue with OpenVAS' report exporting.

**Comment by shall1569** [comment]
Hi @TheGroundZero 

Thanks for your reply. I was unable to raise an issue directly on the OpenVAS Reporting package. 
I have had a look at the XML output that Openvas gives you I can see that it lists the IP address. 

When exporting to CSV it correctly fills in the IP address and the Hostname field. 
I think this is an issue with OpenVas GSA not actually exporting the hostname as part of an xml export. 

Is there any way we are able to use the CSV in your tool?

**Comment by TheGroundZero** [comment]
Currently the OpenVAS Reporting package/tool only supports importing XML and converting this to docx/xlsx/csv.

If you'd like to implement a CSV converter, you're free to create a pull request at the correct repo.

Should I find the time to do so myself, I may add this functionality later on.

EDIT: I've added you're idea to my [TODO list](https://github.com/TheGroundZero/openvasreporting/commit/fb4b32f62d1ebdd8ae1a81fd4b375f8bd613dcd3)

**Comment by shall1569** [comment]
@TheGroundZero 

Not a problem at all. Issue is down to OpenVas itself and not the actual exporting functionality.
I will also post this on the OpenVas community to see if anyone has been able to generate xml reports that contain FQDN's

I appreciate your time.

**Comment by luislopezsanchez** [comment]
I have used several reports generated in Openvas and when applying the examples presented in this documentation to generate the reports either in Word or Excel from the template, the result is always a document without data; the data from the official report cannot be obtained.
Has anyone had the same problem? Any solution?

-----------------------------
He usado varios reportes generados en Openvas y al aplicar los ejemplos planteados en esta documentación para generar los informes ya sea en word o excel a partir de la plantilla, siempre el resultado es un documento sin datos, no se logra obtener los datos del reporte oficial.
alguien le ha pasado igual? alguna solución?

**Comment by luislopezsanchez** [comment]
I have used several reports generated in Openvas and when applying the examples presented in this documentation to generate the reports either in Word or Excel from the template, the result is always a document without data; the data from the official report cannot be obtained.
Has anyone had the same problem? Any solution?

He usado varios reportes generados en Openvas y al aplicar los ejemplos planteados en esta documentación para generar los informes ya sea en word o excel a partir de la plantilla, siempre el resultado es un documento sin datos, no se logra obtener los datos del reporte oficial.
alguien le ha pasado igual? alguna solución?
